trigger: none

schedules:
- cron: "30 4 * * 0,1,2,3,5,6" 
  always: true
  branches:
    include:
    - main
  batch: true
  displayName: Digilær autotest selenium prod
- cron: "0 8 * * 4" 
  always: true
  branches:
    include:
    - main
  batch: true
  displayName: Digilær autotest selenium prod torsdager

pool:
  vmImage: ubuntu-latest

stages:
- stage: run_ui_tests
  displayName: Run UI Tests
  jobs:
    - job: build
      displayName: Build and Test
      continueOnError: false
      timeoutInMinutes: 360
      steps:
        - task: UseDotNet@2
          displayName: 'Using dotnet 5.0.x'
          inputs:
            packageType: 'sdk'
            version: '5.0.x'

        - task: DotNetCoreCLI@2
          displayName: 'Kjør selenium tester skedulert for prod'
          inputs:
            command: 'run'
            arguments: 'chronprod'
            projects: '$(System.DefaultWorkingDirectory)/digilaer-autotest.csproj'
          condition: eq(variables['Build.Reason'], 'Schedule')

        - task: DotNetCoreCLI@2
          displayName: 'Kjør selenium tester prod manuell trigging'
          inputs:
            command: 'run'
            arguments: 'manuellprod'
            projects: '$(System.DefaultWorkingDirectory)/digilaer-autotest.csproj'
          condition: ne(variables['Build.Reason'], 'Schedule')
